version: "3.8"

services:
  dynamodb:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    ports:
      - "127.0.0.1:8000:8000"

  dynamodb-init:
    image: public.ecr.aws/hashicorp/terraform:1.7
    depends_on:
      - dynamodb
    restart: on-failure
    volumes:
      - type: bind
        source: ./db-schemas/dynamodb
        target: /infra
    working_dir: /infra
    entrypoint: "/bin/sh"
    command: ["-c", "terraform init && terraform apply -auto-approve"]
